#!/bin/bash

set -o errexit

# Example that prepares the latest Ruby 3.1 package, from the (extracted) tarball.

export PPA_PAK_PACKAGE_NAME='ruby3.1'
export PPA_PAK_VERSION='3.1.2'
export PPA_PAK_COPYRIGHT='gpl2'
export PPA_PAK_LAUNCHPAD_ID='myuser'
export PPA_PAK_EMAIL='myuser@gmail.com'
export PPA_PAK_DESCRIPTION='Interpreter of object-oriented scripting language Ruby'
export PPA_PAK_HOMEPAGE='https://www.ruby-lang.org/'
export PPA_PAK_DISTROS='jammy'

export PPA_PAK_BUILD_DEPS='autoconf,automake,bison,ca-certificates,curl,libc6-dev,libffi-dev,libgdbm-dev,libncurses5-dev,libsqlite3-dev,libtool,libyaml-dev,make,openssl,patch,pkg-config,sqlite3,zlib1g,zlib1g-dev,libreadline-dev,libssl-dev,libgmp-dev'

"$(dirname "$0")"/../prepare_ppa_package -c /path/to/source_dir
